version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "src.main", "server"]
    ports:
      - "8000:8000"

  client:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "src.main", "client"]
    depends_on:
      - server

  gui:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "src.main", "gui"]
    ports:
      - "8501:8501"
    depends_on:
      - server